#!/usr/bin/python
# Generate possible states of n-blocks world 

import sys

def add_one(configs, b):
	newconfigs = []
	for c in configs:
		newconfigs.extend('{}{}{}'.format(c[:i], b, c[i:]) for i in range(len(c)+1))
		stacks = c.split(',')
		for i in range(len(stacks)+1):
			newconfigs.append(','.join(stacks[0:i] + [b] + stacks[i:]))
	return newconfigs

def all_configs(blocks):
	if not blocks:
		return []
	
	configs = [blocks[0]]
	for b in blocks[1:]:
		configs = add_one(configs, b)
	
	return configs

if __name__ == '__main__':
	if len(sys.argv) < 2:
		print('specify number of blocks', file=sys.stderr)
		sys.exit(1)
		
	blocks = [ chr(x) for x in range(ord('A'), ord('A') + int(sys.argv[1])) ]
	for c in all_configs(blocks):
		print(c)
