#!/bin/sh

if [ ! -f "$1" ]
then
	echo "usage: $0 <line numbers file> <files>" 1>&2
	exit 1
fi

lines=$1
shift

exec awk -v lines="$lines" '
BEGIN {
	while (getline < lines) {
		for (i = 1; i <= NF; ++i) {
			pick[$i] = 1
		}
	}
}
pick[FNR] == 1 { print }' $*
