#!/bin/sh

# Similar to R's summary command
awk '{
	for (i = 1; i <= NF; ++i) {
		if ($i ~ /[-+]?[0-9]*\.?[0-9]*([eE][-+]?[0-9]+)?/) {
			print $i
		}
	}
}' $* | sort -g | awk '{v[NR]=$1; t+=$1} END {
	min = v[1]
	p5   = v[int(1 + (NR-1) * .05)]
	q1   = v[int(1 + (NR-1) * .25)]
	med  = v[int(1 + (NR-1) * .5)]
	mean = t / NR
	q3   = v[int(1 + (NR-1) * .75)]
	p95  = v[int(1 + (NR-1) * .95)]
	max  = v[NR]
	print min, p5, q1, med, mean, q3, p95, max
}'
