#!/bin/sh

ROOT=/tmp/testcode

if [ -z "$1" ]
then
	echo "usage: $0 filename"
	exit 1
fi

if [ ! -d $ROOT ]
then
	mkdir $ROOT
fi

cd $ROOT
file=$1

case "$file" in
*.c)
	hdr="/* gcc $file && ./a.out #*/"
	;;
*.cpp)
	hdr="// g++ $file && ./a.out"
	;;
*.sh)
	hdr="#!/bin/sh"
	;;
*.py)
	hdr="#!/usr/bin/env python"
	;;
esac

if [ ! -f $file ]
then
	echo "$hdr" > $file
fi

while true
do
	vim $file
	cmd=`awk '{
		if (substr($1, 1, 2) == "#!") {
			print "sh"
		} else {
			$1 = ""
			print $0
		}
		exit
	}' $file`
	eval "$cmd"

	echo -n 'Again? '
	read again
	if [ "$again" == "n" ]
	then
		exit
	fi
done

