#!/bin/sh

awk '
BEGIN { print "digraph {" }
{ 
	gsub(/[()]/,"");
	printf("edge [label=\"%s\"];\n", substr($2, 2));
	printf("%s [shape=box];\n", $1);
	if ($3 ~ /[A-Z][0-9]+/) {
		printf("%s -> %s;\n", $1, $3)
	} else {
		printf("const%d [shape=plaintext,label=\"%s\"];\n", c, $3)
		printf("%s -> const%d;\n", $1, c++)
	}
}

END { print "}"}
'
